name: zsdk
description: A Flutter plugin for printers using Zebra Link OS, to allow ZPL and PDF priting over TCP/IP connections.
version: 4.0.0
homepage: https://github.com/luis901101/zsdk
issue_tracker: https://github.com/luis901101/zsdk/issues
topics:
  - zebra
  - thermal
  - ticket
  - printer

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: '>=3.32.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.2
  pigeon: ^26.1.0
  pigeon_generator: ^3.1.0
  json_serializable: ^6.11.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.flutter.zsdk
        pluginClass: ZsdkPlugin
      ios:
        pluginClass: ZsdkPlugin
